# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbuz_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('crimes_coefficient', models.FloatField()),
            ],
        ),
    ]
