# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbuz_core', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
