# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbuz_core', '0003_auto_20160520_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
